version: '3.8'
services:
  bookstoremanagementnestjs:
    container_name: bookStoreManagementNestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    container_name: bookStoreManagementPostgresSQL
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "bookstore_postgres"
      POSTGRES_PASSWORD: "Burak1995"
      POSTGRES_DB: bookstore
    ports:
      - '5433:5432'
  rabbitmq:
    container_name: bookStoreManagementRabbitMQ
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
